# Generated by Django 3.1.13 on 2021-11-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopreading',
            name='gtin',
            field=models.CharField(max_length=255, verbose_name='Global Trade Identification Number'),
        ),
    ]
